# -*- coding: utf-8 -*-
"""Video Game Sales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8gCK9LrtTLuVVFLUaQvs1KHPDpH-eFD
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

vgsales = pd.read_csv("/content/game.zip")
data = vgsales.head()
print(data)

print(vgsales["Genre"].value_counts())

print(vgsales.columns)

sales_total = vgsales[['NA_Sales','Other_Sales', 'JP_Sales', 'Other_Sales']].sum()
sales_total.plot(kind='pie',colors = ['#FFB3BA', '#FFDFBA', '#FFFFBA', '#BAFFC9'],autopct='%1.1f%%',textprops={"fontsize":11, "fontweight":"bold"}, label = "Sales of Global Sales")
plt.legend(loc = "upper right",bbox_to_anchor=(1.28, 1.15))
plt.xlabel("Global Sales")
plt.title("Global Sales Pie Chart")
plt.savefig(r"C:\Users\mirfe\OneDrive\Masaüstü\dataset\global_sales_pie_chart.png", dpi=300, bbox_inches='tight')
plt.show()

vgname = vgsales[['Name','Global_Sales']].copy()
vgname.sort_values(by=['Global_Sales'], ascending=False, inplace=True)
top10 =vgname.head(10)

plt.figure(figsize=(12,6))
plt.figure(figsize = (12,6))
plt.bar(top10["Name"], top10["Global_Sales"], color="skyblue")
plt.title("Best-Selling Video Games #TOP10")
plt.xlabel("Video Game")
plt.ylabel("Global Sales (Million)")
plt.xticks(rotation=45)
bars = plt.bar(top10["Name"], top10["Global_Sales"], color="skyblue")
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, yval, bar.get_height(), ha="center", va="bottom")
plt.tight_layout()
plt.show()

vgname = vgsales[['Name','NA_Sales']].copy()
vgname.sort_values(by=['NA_Sales'], ascending=False, inplace=True)
top10_na =vgname.head(10)

plt.figure(figsize=(12,6))
plt.figure(figsize = (12,6))
plt.bar(top10_na["Name"], top10_na["NA_Sales"], color="skyblue")
plt.title("Best-Selling Video Games in North America #TOP10")
plt.xlabel("Video Game")
plt.ylabel("NA_Sales (Million)")
plt.xticks(rotation=45)
bars = plt.bar(top10_na["Name"], top10_na["NA_Sales"], color="skyblue")
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, yval, bar.get_height(), ha="center", va="bottom")
plt.tight_layout()
plt.show()

vgname = vgsales[['Name','Other_Sales']].copy()
vgname.sort_values(by=['Other_Sales'], ascending=False, inplace=True)
top10_os =vgname.head(10)

plt.figure(figsize=(12,6))
plt.figure(figsize = (12,6))
plt.bar(top10_os["Name"], top10_os["Other_Sales"], color="skyblue")
plt.title("Best-Selling Video Games in Other Countries #TOP10")
plt.xlabel("Video Game")
plt.ylabel("Other_Sales (Million)")
plt.xticks(rotation=60)
bars = plt.bar(top10_os["Name"], top10_os["Other_Sales"], color="skyblue")
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, yval, bar.get_height(), ha="center", va="bottom")
plt.tight_layout()
plt.show()

vgsales_clean = vgsales.dropna(subset=["Year"])
year_counts = vgsales_clean["Year"].value_counts()
top5_years = year_counts.nlargest(5)
plt.figure(figsize=(8, 8))
plt.pie(top5_years, labels=top5_years.index.astype(int), autopct='%1.1f%%', startangle=90)
plt.title("The 5 Years with the Most Game Releases")
plt.axis('equal')  # Daire düzgün çıksın
plt.show()

vgsales_clean = vgsales.dropna(subset=["Publisher"])
publisher_counts = vgsales_clean["Publisher"].value_counts()
top5_publisher = publisher_counts.nlargest(5)
plt.figure(figsize=(8, 8))
plt.pie(top5_publisher, labels=top5_publisher.index, autopct='%1.1f%%', startangle=90)
plt.title("The 5 Publisher with the Most Game Releases")
plt.axis('equal')  # Daire düzgün çıksın
plt.show()

vgsales_clean = vgsales.dropna(subset=["Publisher"])
publisher_counts = vgsales_clean["Publisher"].value_counts()
top5_publisher = publisher_counts.head(5)
colors = plt.get_cmap('Set3').colors  # pastel tonlar
plt.figure(figsize=(10, 8))
wedges, texts, autotexts = plt.pie(
    top5_publisher,
    labels=top5_publisher.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=colors,
    wedgeprops={'edgecolor': 'white', 'linewidth': 1.5}
)
for text in texts:
    text.set_fontsize(12)
    text.set_color('black')

for autotext in autotexts:
    autotext.set_fontsize(12)
    autotext.set_color('black')
    autotext.set_weight('bold')

plt.title("Top 5 Game Publisher", fontsize=16, fontweight='bold')
plt.axis('equal')
plt.tight_layout()
plt.show()

vgsales_clean = vgsales.dropna(subset=["Genre"])
genre_counts = vgsales_clean["Genre"].value_counts()
top5_genre = genre_counts.head(5)
colors = plt.get_cmap('Set3').colors  # pastel tonlar
plt.figure(figsize=(10, 8))
wedges, texts, autotexts = plt.pie(
    top5_publisher,
    labels=top5_genre.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=colors,
    wedgeprops={'edgecolor': 'white', 'linewidth': 1.5}
)
for text in texts:
    text.set_fontsize(12)
    text.set_color('black')

for autotext in autotexts:
    autotext.set_fontsize(12)
    autotext.set_color('black')
    autotext.set_weight('bold')


plt.title("Top 5 Game Genre", fontsize=16, fontweight='bold')
plt.axis('equal')
plt.tight_layout()
plt.show()

vgsales_clean = vgsales.dropna(subset=["Genre"])
genre_counts = vgsales_clean["Genre"].value_counts()
top5_genre = genre_counts.head(10)
plt.figure(figsize=(10, 6))
bars = plt.bar(top5_genre.index, top5_genre.values, color='skyblue', edgecolor='black')

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 5, f"{yval}", ha='center', va='bottom', fontsize=11, fontweight='bold')

plt.title("The Most Played Games By Type", fontsize=14, fontweight='bold')
plt.xlabel("Type", fontsize=12)
plt.ylabel("Game Count", fontsize=12)
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.show()